services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pharaon
    restart: unless-stopped
    ports:
      - "80:8080"
      - "5173:5173"
    volumes:
      - .:/var/www/html
    environment:
      - SSL_MODE=off
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: pharaon-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: